apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels: { app: demo-api }
spec:
  replicas: 2
  selector: { matchLabels: { app: demo-api } }
  template:
    metadata: { labels: { app: demo-api } }
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports: [ { name: http, containerPort: 8080 } ]
          env: [ { name: LISTEN_ADDR, value: ":8080" } ]
          readinessProbe: { httpGet: { path: "/", port: http }, initialDelaySeconds: 5, timeoutSeconds: 2 }
          livenessProbe:  { httpGet: { path: "/", port: http }, initialDelaySeconds: 10, timeoutSeconds: 2 }
