apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
  labels: { app: hpa-demo }
spec:
  replicas: 1
  selector: { matchLabels: { app: hpa-demo } }
  template:
    metadata: { labels: { app: hpa-demo } }
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports: [ { containerPort: 80 } ]
          resources:
            requests: { cpu: "200m", memory: "128Mi" }
            limits: { cpu: "1000m", memory: "256Mi" }
