apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
  labels: { app: hpa-demo }
spec:
  type: ClusterIP
  selector: { app: hpa-demo }
  ports:
    - name: http
      port: 80
      targetPort: 80
