apiVersion: v1
kind: Service
metadata:
  name: demo-api
  labels: { app: demo-api }
spec:
  type: ClusterIP
  selector: { app: demo-api }
  ports:
    - name: http
      port: 80
      targetPort: 8080
