apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels: { app: demo-api }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector: { matchLabels: { app: demo-api } }
  template:
    metadata: { labels: { app: demo-api } }
    spec:
      containers:
        - name: api
          image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          ports: [ { name: http, containerPort: 8080 } ]
          env:
            - name: LISTEN_ADDR
              value: ":8080"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef: { name: demo-api-config, key: APP_ENV }
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
