apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - ../../base
patches:
  - target: { kind: ConfigMap, name: fb-env }
    patch: |-
      - op: replace
        path: /data/CW_REGION
        value: us-east-1
      - op: replace
        path: /data/CW_LOG_GROUP
        value: /eks/logging/staging
  - target: { kind: ServiceAccount, name: fluent-bit }
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::<ACCOUNT_ID>:role/fb-cloudwatch-role-stg
