apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: demo-api
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
